on:
  schedule:
    - cron: '00 12 * * 1-5'
jobs:
  release:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git fetch --prune --unshallow
      - run: git checkout develop
      - run: git config --local user.email "matt@mattriley.me"
      - run: git config --local user.name "Matt Riley"
      - run: git checkout -b release
      - name: npm cache
        id: npm-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
      - name: Install Deps if no cache
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci --silent
      - run: npm run release
      - run: git remote set-url origin https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
      - run: git push origin release
